name = "absensi-sd-ypu"
compatibility_date = "2026-05-28"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "buildypu"
database_id = "5b4a1cb8-f1ae-48bc-998b-3923107e5a4f"
